"""initial

Revision ID: eada068e03e4
Revises: 
Create Date: 2026-05-10 08:29:21.713688+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eada068e03e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('spotify_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('followed', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('spotify_id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('sync_status',
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('venues',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('alias_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.spotify_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_aliases_alias_name'), 'artist_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_artist_aliases_artist_id'), 'artist_aliases', ['artist_id'], unique=False)
    op.create_table('concerts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('venue_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('stage_times', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concerts_date'), 'concerts', ['date'], unique=False)
    op.create_index(op.f('ix_concerts_is_read'), 'concerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_concerts_venue_id'), 'concerts', ['venue_id'], unique=False)
    op.create_table('releases',
    sa.Column('spotify_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('album_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.spotify_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spotify_id')
    )
    op.create_index(op.f('ix_releases_artist_id'), 'releases', ['artist_id'], unique=False)
    op.create_index(op.f('ix_releases_is_read'), 'releases', ['is_read'], unique=False)
    op.create_index(op.f('ix_releases_release_date'), 'releases', ['release_date'], unique=False)
    op.create_table('vinyl_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('spotify_album_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('original_release_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('pressing_info', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_store', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('purchase_price', sa.Integer(), nullable=True),
    sa.Column('purchase_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('favorite_tracks', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.spotify_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vinyl_records_artist_id'), 'vinyl_records', ['artist_id'], unique=False)
    op.create_index(op.f('ix_vinyl_records_display_order'), 'vinyl_records', ['display_order'], unique=False)
    op.create_index(op.f('ix_vinyl_records_spotify_album_id'), 'vinyl_records', ['spotify_album_id'], unique=False)
    op.create_table('concert_artists',
    sa.Column('concert_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.spotify_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concert_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concert_artists')
    op.drop_index(op.f('ix_vinyl_records_spotify_album_id'), table_name='vinyl_records')
    op.drop_index(op.f('ix_vinyl_records_display_order'), table_name='vinyl_records')
    op.drop_index(op.f('ix_vinyl_records_artist_id'), table_name='vinyl_records')
    op.drop_table('vinyl_records')
    op.drop_index(op.f('ix_releases_release_date'), table_name='releases')
    op.drop_index(op.f('ix_releases_is_read'), table_name='releases')
    op.drop_index(op.f('ix_releases_artist_id'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_concerts_venue_id'), table_name='concerts')
    op.drop_index(op.f('ix_concerts_is_read'), table_name='concerts')
    op.drop_index(op.f('ix_concerts_date'), table_name='concerts')
    op.drop_table('concerts')
    op.drop_index(op.f('ix_artist_aliases_artist_id'), table_name='artist_aliases')
    op.drop_index(op.f('ix_artist_aliases_alias_name'), table_name='artist_aliases')
    op.drop_table('artist_aliases')
    op.drop_table('venues')
    op.drop_table('sync_status')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
